# Generated by Django 6.0.6 on 2026-06-16 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointment", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("CANCELLATION_FEE", "Cancellation Fee"),
                            ("NO_SHOW_FEE", "No Show Fee"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_url", models.URLField(blank=True, max_length=355, null=True)),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="appointment.appointment",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
