# Generated by Django 6.0.6 on 2026-06-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
