services:
  db:
    image: postgres:15-alpine
    container_name: clinic_postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
      build: .
      container_name: clinic_django_api
      restart: always
      command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      env_file:
        - .env
      depends_on:
        db:
          condition: service_healthy

volumes:
  postgres_data: